### PR TITLE
Update calendar_date_select.rb

### PR DESCRIPTION
**Pull request by zedtux**
Includes FormHelpers and IncludesHelper in the `ActionView::Base` instead of `ActionView::Helpers`.

### CODE REVIEW

**Comment by zedtux** [comment]
Using this gem alone was working fine until I start to use another gem which was doing a `ActionView::Base.send(:include, ...)`.

I don't understand why, but the next gem doing the include on the `ActionView::Base` removes the `calendar_data_select_tag`.
This commit make all working all together.

**Comment by zedtux** [comment]
@timcharper any chance you have a look at this PR please?

**Comment by zedtux** [comment]
@marcandre can you please have a look at this PR?

**Comment by marcandre** [comment]
I think this gem is not really supported anymore. Moreover I don't understand the details of this change, nor how your original issue happens, sorry...

**Comment by zedtux** [comment]
Thank you @marcandre for your comment.

> I think this gem is not really supported anymore.

I can believe it but unfortunately the project I'm migrating is using it and we aren't ready to remove it yet (but should happen one day).

> I don't understand the details of this change, nor how your original issue happens

This change fixes the compatibility of this gem with other gems injecting view helpers in Rails.
This gem works when running alone, but adding another gem injecting helpers makes calendar_date_select no more working.

This PR fixes this by using the _normal_ way of adding helpers in the view context.

**Comment by zedtux** [comment]
I'm no more working on that migration project, closing the PR.

**Pull request closed without merging**
